src/managers/queue-manager.js

Task: https://github.com/customerio/issues/issues/8677

Handle undefined response when polling messages

---

src/managers/message-manager.js

Addresses: https://github.com/customerio/issues/issues/9268

Added timer to calculate time to render message

---

src/managers/message-manager.js

This fixes the following issue: https://github.com/customerio/issues/issues/10157

Make sure currentMessage exist

---

src/managers/queue-manager.js

Fixes issue here: https://github.com/customerio/issues/issues/11663

Added a sort call to make sure messages are always pulled by priority

---

.github/workflows/release.yml
.github/workflows/trigger-release.yml
LICENSE
package.json

There are 2 changes here:
- added publish of the npm package in release.yml - this depends on the existence of NPM_TOKEN in the secrets
- added trigger a release action which takes a semver instruction and releases to master
Task: https://github.com/customerio/issues/issues/11709

Publish NPM package

---

.github/workflows/trigger-release.yml

Fix the options dropdown for the release trigger

Fix release options

---

src/managers/message-manager.js

Addresses: https://github.com/customerio/issues/issues/11714

Always propagate message view event

---

package.json

This allows both CJS and ESM projects to import this library.

Add support for ESM

---

.github/workflows/release_hotfix.yml
.github/workflows/release_version.yml

Task: https://github.com/customerio/issues/issues/11921
It now sets the package.json version using npm, commits that to develop, then continues with the release

Update package.json version during release

---

src/managers/message-manager.js
src/managers/queue-manager.js
src/services/queue-service.js

Fixes: https://customerio.slack.com/archives/C036FTE6UJ0/p1709055145606009
Beta SDK: https://code.gist.build/web/3.7.1B/gist.min.js

Added timestamp to Queue URL and Updated local store logic

---

src/managers/message-manager.js

Issue: https://customerio.slack.com/archives/C036FTE6UJ0/p1710885296297509

Fixes an issue where persistent messages were being removed from the local queue on show

---

.github/workflows/release.yml
.github/workflows/release_hotfix.yml
.github/workflows/release_version.yml

This reverts commit 938cebb5e32f28fdecf31aaf678451d5e778012e, reversing changes made to 6a0737d38bafab4102fb1b155314aa75a39d922f.

Revert "move to self-hosted, ephemeral runners (#51)"

---

src/gist.js
src/managers/message-broadcast-manager.js
src/managers/message-user-queue-manager.js
src/managers/user-manager.js
src/services/queue-service.js
src/utilities/local-storage.js
src/utilities/preview-mode.js

Issue: https://linear.app/customerio/issue/INAPP-12601/add-support-for-ciopreviewid-to-launch-sdk-in-preview-mode

Using cioPreviewId to make SDK enter preview mode

---

src/managers/message-broadcast-manager.js

[in-app-broadcast] Add support for unlimited frequency

---

src/managers/message-broadcast-manager.js

add ignoreDismiss support to message broadcast manager

---

src/managers/message-broadcast-manager.js
src/managers/message-manager.js
src/managers/message-user-queue-manager.js
src/managers/queue-manager.js

Addresse: https://customerio.slack.com/archives/C036FTE6UJ0/p1737058738776549

Fixes an issue where a single message can load on multiple tabs / windows

---

src/gist.js
src/managers/message-manager.js

Addresses: https://linear.app/customerio/issue/INAPP-13081/address-action-handling-within-in-app-web-sdk

Address action handling within In-app Web SDK

---

package-lock.json
package.json

Leftovers from PR https://github.com/customerio/gist-web/pull/82
Part of INAPP-13292

Remove Axios from Dependencies

---

src/managers/message-component-manager.js
src/managers/queue-manager.js

Part of: https://linear.app/customerio/issue/INAPP-12666/remove-flutter-renderer-warm-up-call

Removes legacy renderer preloading

---

src/managers/queue-manager.js

Part of: https://linear.app/customerio/issue/INAPP-13632/call-queue-consumer-on-sse-connection

SDK now performs a queue check on successful SSE connection

---

src/utilities/log.js

Part of: https://linear.app/customerio/issue/INAPP-13903/inject-anonymous-id-to-lead-form-submission

Prevents SDK crash if logging hasn't been setup yet
