customerio/gist-web

.github/workflows/build.yml, .github/workflows/release.yml
Build on merge to develop
Release on tag creation
Task: https://github.com/customerio/issues/issues/9599
=> Build and release pipelines for Gist Web

src/managers/message-manager.js
Fixes a number of issues when the gist object is not present. Instead of using the message object directly, we're using the resolveMessageProperies function to get the appropriate defaults.
=> Fixes a number of issues when the gist object is not present

src/managers/queue-manager.js
Since the 304 response has an empty body, the local queue was being cleared.
=> Fixes an issue where if a 304 was returned, the queue was being cleared.

src/managers/queue-manager.js
This should fix an issue with persistent messages disappearing after refreshing the browser, issue is detailed here: https://customerio.slack.com/archives/C036FTE6UJ0/p1694744921889529
For now, we're just caching the response output and storing it in the browser's local store, very similar to how iOS does it natively.
Eventually, when other features we're working on are introduced, the local queue will switch to the browser's local store.
=> Caching 304 responses in local store

src/gist.js, src/managers/message-component-manager.js, src/managers/message-manager.js, src/managers/queue-manager.js
This PR addresses 2 issues:
1. On some rare occasions, shown messages were being shown twice. [Slack Thread](https://customerio.slack.com/archives/C01QYDKD0SU/p1697828787602979?thread_ts=1696992122.437309&cid=C01QYDKD0SU)
2. When users had multiple messages queued up, there was a possibility for the queue to get stuck in a state where modal messages wouldn't be shown (unless page is refreshed).
=> Duplicate views and multiple messages fixes.

index.d.ts
Allows `customerio-gist-web` to be imported properly in TS projects.
=> Fix module name declaration

package-lock.json, package.json
Add html-loader as prod dependency, otherwise we can't build from `cdp-analytics-js` because of: https://github.com/customerio/gist-web/blob/develop/src/managers/message-component-manager.js#L136
=> html-loader as prod dependency

.github/workflows/release_hotfix.yml, .github/workflows/release_version.yml
As a public repo, it turns out gist-web cannot share the gist-workflows workflows
=> Use local steps for the actions

src/templates/message.js
Addresses issue: https://linear.app/customerio/issue/INAPP-12340/when-another-modal-exists-on-screen-pointer-events-pass-through-in-app
=> Forces a visible message to intercept pointer events

src/managers/page-component-manager.js
This work is part of: https://linear.app/customerio/issue/INAPP-12366/render-iframe-title-attribute-should-be-set-to-message-title-value
=> Changes the position where embedded messages are injected in the DOM

src/managers/message-component-manager.js, src/managers/page-component-manager.js, src/templates/embed.js
Inline message width is now respected if more than one inline message is loaded on the page.
Issue: https://customerio.slack.com/archives/C036FTE6UJ0/p1713485101645209
=> Fixes inline message width

package-lock.json, package.json
part of [INAPP-12464](https://linear.app/customerio/issue/INAPP-12464/update-axios-version-so-that-customeriocdp-analytics-browser-is-not)
Tested it using npm-shrinkwrap and pointed customerio-gist-web to local for cdp-analytics-browser.
=> upgrade axios to latest v0.28.1 + npm audit fix

src/managers/message-component-manager.js, src/templates/embed.js, src/templates/message.js
Issue: https://linear.app/customerio/issue/INAPP-12467/overlay-width-settings-triggering-100percent-width-in-gist-web-sdk
=> Fixes the issue where in some cases if an overlay goes over the max width, all overlays switch to 100%.

src/templates/embed.js, src/templates/message.js
As a side effect, we get embedded messages that load in softer.
**Side Effect Off**
https://github.com/customerio/gist-web/assets/346012/e90492bc-27b3-4387-9c7e-e7b822c96a24
**Side Effect On**
https://github.com/customerio/gist-web/assets/346012/e4ec8a4c-b8d8-4f52-ad1a-2c1f8a6b02a2
=> Smoothens out message resizing

src/gist.js, src/services/queue-service.js
- Removed unused import, `DefaultHeaders`in `src/services/queue-service.js`, it was never defined in `src/services/network.js`
- Removed unused import, `fetchPreviewId` in `src/gist.js`, it was defined but not exported from `src/utilities/preview-mode.js`.
=> Removed unused variable that caused a crash on the VIte runtime environment.

src/managers/message-broadcast-manager.js, src/managers/message-manager.js
Part of INAPP-12844
Updating a default behavior, i.e if a user dismisses an anonymous message, lets not pester them with showing it again. 
We're planning to make it configurable in a future release.
=> [in-app-broadcast] hide anonymous message if user dismisses it

src/managers/message-component-manager.js, src/managers/message-manager.js, src/services/settings.js
Linear issue: https://linear.app/customerio/issue/INAPP-12777/request-header-too-large-preventing-in-app-messages-from-rendering
The plan is to pass the data to the iframe using postMessage instead of using a query parameter. If I can figure out how to do this for android I think we may be ok
=> Support larger rendering input

src/services/settings.js
Linear issue: https://linear.app/customerio/issue/INAPP-12777/request-header-too-large-preventing-in-app-messages-from-rendering
This is technically the same version as the beta, but we need to use the proper url for the release.
=> Update to the latest renderer

src/managers/gist-properties-manager.js, src/managers/message-component-manager.js
When the `exitClick` property is set to true, we add a dismiss listener to modal messages.
Part of: [INAPP-12673](https://linear.app/customerio/issue/INAPP-12673/feature-request-in-app-allow-customer-to-configure-if-clicking-outside)
=> Added exitClick handling

src/gist.js, src/managers/message-manager.js, src/managers/queue-manager.js, src/managers/user-manager.js, src/services/network.js, src/services/queue-service.js, src/services/settings.js
Part of: [INAPP-13259](https://linear.app/customerio/issue/INAPP-13259/implement-web-sdk-changes-to-enable-sse-support)
=> Adds realtime through SSE

src/managers/message-component-manager.js, src/managers/queue-manager.js, src/templates/message.js
Prefixed styles with `gist-` to make sure there are no collisions with other site styles.
Addresses: [INAPP-13637](https://linear.app/customerio/issue/INAPP-13637/in-app-messages-are-not-visible-when-site-loads-twindstyle-plugin)
=> Prefixed CSS Styles

src/managers/message-broadcast-manager.js, src/managers/message-user-queue-manager.js, src/utilities/local-storage.js
Addresses: [INAPP-13728](https://linear.app/customerio/issue/INAPP-13728/expired-anonymous-in-app-messages-continue-to-display-and-track)
=> Sets local store expiry to 10 minutes for broadcasts and user queue.
